name: talawa
description: Welcome to the Talawa Project for the Palisadoes Foundation
  Community Organization Management Software.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

homepage: https://github.com/PalisadoesFoundation/talawa

repository: https://github.com/PalisadoesFoundation/talawa

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ############# Remove ###########
  _fe_analyzer_shared: ^52.0.0
  analyzer:
  analyzer_plugin:
  ################################
  
  auto_size_text: ^3.0.0
  cached_network_image: ^3.1.0
  connectivity_plus: ^3.0.0
  cupertino_icons: ^1.0.3
  currency_picker: ^2.0.16

  ############## Remove ##########
  custom_lint_builder: ^0.2.12
  ################################
  
  file: ^6.1.4
  firebase_core: ^2.6.1
  firebase_core_platform_interface: ^4.5.3
  firebase_messaging: ^14.4.1
  firebase_messaging_platform_interface: ^4.2.16
  flutter:
    sdk: flutter

  flutter_braintree: ^3.0.0
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^14.0.0
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^6.2.0
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.3.0
  google_maps_flutter: ^2.2.5
  graphql_flutter: ^5.1.2
  hive: ^2.2.3
  http: ^0.13.3
  image_cropper: ^3.0.3
  image_picker: ^0.8.7
  intl: ^0.17.0
  json_annotation: ^4.7.0
  mockito: ^5.3.2
  network_image_mock: ^2.1.1
  path_provider: ^2.0.2
  permission_handler: ^10.2.0
  plugin_platform_interface: ^2.1.3
  provider: ^6.0.3
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  quick_actions: ^1.0.1
  shared_preferences: ^2.1.0
  shimmer: ^2.0.0
  social_share: ^2.2.1
  syncfusion_flutter_calendar: ^20.4.54
  syncfusion_flutter_datepicker: ^20.2.38
  timelines: ^0.1.0
  tutorial_coach_mark: ^1.2.8
  uni_links: ^0.5.1
  vibration: ^1.7.6
  video_player: ^2.6.0
  visibility_detector: ^0.4.0+2



dev_dependencies:
  build_runner: ^2.3.3
  custom_lint:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1
  lint: ^2.0.1
  mocktail_image_network: ^0.3.1
  talawa_lint:
    path: talawa_lint/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - lang/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: product-sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 800
    - family: open-sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 800
  #       - asset:
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets\fonts\OpenSans-Bold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
