name: talawa
description: Welcome to the Talawa Project for the Palisadoes Foundation
  Community Organization Management Software.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

homepage: https://github.com/PalisadoesFoundation/talawa

repository: https://github.com/PalisadoesFoundation/talawa
environment:
  sdk: ">=3.5.0 <4.0.0"

dependency_overrides:
  # Intentional override to resolve diamond dependency conflict between:
  # - hive_generator (requires analyzer >=4.6.0 <7.0.0)
  # - talawa_lint (requires analyzer >=6.4.0 <8.0.0)
  # - Flutter SDK (requires newer analyzer)
  #
  # Targeted range <8.0.0 is used to prevent breaking changes in talawa_lint
  # while satisfying other dependencies.
  # Revisit this when hive_generator is updated to support analyzer >=7.0.0.
  analyzer: ">=6.0.0 <7.0.0"
  dart_style: 2.3.6
dependencies:
  # _fe_analyzer_shared: ^60.0.0
  # analyzer:
  # analyzer_plugin:

  app_links: ^6.4.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.5
  contained_tab_bar_view: ^0.8.0

  crypto: ^3.0.5
  currency_picker: ^2.0.21
  ############## Remove ##########

  # custom_lint_builder: ^0.4.0
  ################################
  delightful_toast: ^1.1.0

  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^6.0.0
  flutter_image_compress: ^2.4.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.3
  flutter_windowmanager_plus: ^1.0.1
  get_it: ^9.2.0
  graphql_flutter: ^5.2.1
  hive: ^2.2.3
  http: ^1.5.0
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  intl: ^0.20.0
  mockito: ^5.4.4
  path_provider: ^2.1.5

  pointycastle: ^4.0.0
  provider: ^6.1.5
  qr_code_scanner_plus: ^2.0.14
  qr_flutter: ^4.1.0
  quick_actions: ^1.1.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  syncfusion_flutter_calendar: ^30.2.6
  syncfusion_flutter_datepicker: ^30.2.6
  timelines_plus: ^1.0.7
  tutorial_coach_mark: ^1.3.1
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  vibration: ^3.1.5
  video_player: ^2.10.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  _fe_analyzer_shared: any
  analyzer: any
  analyzer_plugin: ">=0.11.3 <0.14.0"
  args: ^2.7.0
  build_runner: ^2.4.13
  clock: ^1.1.2
  custom_lint: 0.6.4
  custom_lint_builder: 0.6.4
  dependency_validator: ^5.0.0
  fake_async: ^1.3.1
  file: ^7.0.1
  flutter_test:
    sdk: flutter
  gql: ^1.0.1
  graphql: ^5.2.3
  hive_generator: ^2.0.1

  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  lint: ^2.7.0
  test: ^1.24.0

  mocktail_image_network: ^1.2.0
  network_image_mock: ^2.1.1
  normalize: ^0.9.1
  plugin_platform_interface: ^2.1.8

  talawa_lint:
    path: talawa_lint/

  url_launcher_platform_interface: 2.3.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - lang/
  fonts:
    - family: product-sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 800
    - family: open-sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 800
