name: talawa
description: Welcome to the Talawa Project for the Palisadoes Foundation
  Community Organization Management Software.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

homepage: https://github.com/PalisadoesFoundation/talawa

repository: https://github.com/PalisadoesFoundation/talawa
environment:
  sdk: ">=2.17.0 <=3.6.2"

dependencies:
  ############# Remove ###########
  # _fe_analyzer_shared: ^60.0.0
  # analyzer:
  # analyzer_plugin:
  ################################

  app_links: ^6.3.3
  app_links_platform_interface: ^2.0.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  clock: ^1.1.1
  connectivity_plus: ^6.1.4
  contained_tab_bar_view: ^0.8.0

  crypto: ^3.0.5
  cupertino_icons: ^1.0.8
  currency_picker: ^2.0.21
  ############## Remove ##########

  # custom_lint_builder: ^0.4.0
  ################################
  delightful_toast: ^1.1.0
  file: ^7.0.1

  flutter:
    sdk: flutter
  flutter_braintree: ^4.0.0
  flutter_cache_manager: ^3.4.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_reaction_button: ^3.0.0+3
  flutter_secure_storage: ^9.2.4
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  graphql_flutter: ^5.2.0-beta.8
  hive: ^2.2.3
  http: ^1.3.0
  image_cropper: 9.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.7.0
  mockito: ^5.4.4
  network_image_mock: ^2.1.1
  path_provider: ^2.1.5
  permission_handler: 11.3.1
  plugin_platform_interface: ^2.1.7
  pointycastle: ^4.0.0
  provider: ^6.1.2
  qr_code_scanner_plus: ^2.0.9+1
  qr_flutter: 4.1.0
  quick_actions: ^1.1.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  stack_trace: ^1.11.1
  syncfusion_flutter_calendar: ^28.2.3
  syncfusion_flutter_datepicker: ^28.2.3
  timelines_plus: ^1.0.6
  tutorial_coach_mark: ^1.2.13
  url_launcher: ^6.3.1
  vibration: ^2.0.1
  video_player: ^2.9.3
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: 0.7.0
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

  json_serializable: ^6.8.0
  lint: ^2.7.0

  mocktail_image_network: ^1.2.0
  talawa_lint:
    path: talawa_lint/

  url_launcher_platform_interface: 2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - lang/
  fonts:
    - family: product-sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 800
    - family: open-sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 800
