name: talawa
description: Welcome to the Talawa Project for the Palisadoes Foundation
  Community Organization Management Software.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

homepage: https://github.com/PalisadoesFoundation/talawa

repository: https://github.com/PalisadoesFoundation/talawa

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  connectivity_plus: ^1.0.7
  cupertino_icons: ^1.0.3
  currency_picker: 2.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^4.2.0
  font_awesome_flutter: ^9.1.0
  get_it: ^7.2.0
  graphql_flutter: ^5.0.0
  hive: ^2.0.4
  http: ^0.13.3
  image_cropper: ^1.4.1
  image_picker: ^0.8.1+3
  intl: ^0.17.0
  json_annotation: ^4.0.1
  mockito: ^5.0.14
  path_provider: ^2.0.2
  provider: ^5.0.0
  qr_code_scanner: ^0.5.2
  qr_flutter: ^4.0.0
  quick_actions: ^0.6.0+5
  razorpay_flutter: ^1.2.7
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  social_share: ^2.2.1
  timelines: ^0.1.0
  tutorial_coach_mark: ^1.1.1
  uni_links: ^0.5.1
  vibration: ^1.7.4-nullsafety.0
  video_player: ^2.2.7
  visibility_detector: ^0.2.2

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  json_serializable: ^4.1.3
  lint: ^1.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - lang/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: product-sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 800
    - family: open-sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 800
  #       - asset:
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets\fonts\OpenSans-Bold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
