name: talawa
description: Welcome to the Talawa Project for the Palisadoes Foundation
  Community Organization Management Software.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

homepage: https://github.com/PalisadoesFoundation/talawa

repository: https://github.com/PalisadoesFoundation/talawa
environment:
  sdk: ">=2.17.0 <=3.22.3"

dependencies:
  ############# Remove ###########
  # _fe_analyzer_shared: ^60.0.0
  # analyzer:
  # analyzer_plugin:
  ################################

  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^5.0.2
  contained_tab_bar_view: ^0.8.0

  crypto: ^3.0.5
  cupertino_icons: ^1.0.8
  currency_picker: ^2.0.21
  ############## Remove ##########

  # custom_lint_builder: ^0.4.0
  ################################
  delightful_toast: ^1.1.0
  file: ^7.0.0

  flutter:
    sdk: flutter
  flutter_braintree: ^4.0.0
  flutter_cache_manager: ^3.4.1
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  flutter_reaction_button: ^3.0.0+3
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get_it: ^8.0.0
  graphql_flutter: ^5.1.2
  hive: ^2.2.3
  http: ^1.2.2
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.7.0
  mockito: ^5.4.4
  network_image_mock: ^2.1.1
  path_provider: ^2.1.4
  permission_handler: 11.3.1
  plugin_platform_interface: ^2.1.7
  pointycastle: ^3.9.1
  provider: ^6.1.2
  qr_code_scanner: ^1.0.0
  qr_flutter: 4.1.0
  quick_actions: ^1.0.6
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  social_share: ^2.2.1
  syncfusion_flutter_calendar: ^27.1.48
  syncfusion_flutter_datepicker: ^27.1.48
  timelines: ^0.1.0
  tutorial_coach_mark: ^1.2.11
  uni_links: ^0.5.1
  uni_links_platform_interface: ^1.0.0
  url_launcher: ^6.3.0
  vibration: ^2.0.0
  video_player: ^2.9.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: 0.5.8
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

  json_serializable: ^6.8.0
  lint: ^2.3.0

  mocktail_image_network: ^1.2.0
  talawa_lint:
    path: talawa_lint/

  url_launcher_platform_interface: 2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - lang/
  fonts:
    - family: product-sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 800
    - family: open-sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 800
