name: talawa
description: Welcome to the Talawa Project for the Palisadoes Foundation
  Community Organization Management Software.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

homepage: https://github.com/PalisadoesFoundation/talawa
repository: https://github.com/PalisadoesFoundation/talawa

environment:
  sdk: ">=2.17.0 <=3.9.2"

dependencies:
  flutter:
    sdk: flutter
  
  app_links: ^6.3.3
  cloud_firestore: ^5.6.12
  connectivity_plus: ^6.1.5
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  firebase_auth: ^5.3.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.0.0
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^18.0.1
  flutter_secure_storage: ^9.2.2
  font_awesome_flutter: ^10.6.0
  get_it: ^8.0.0
  graphql_flutter: ^5.2.0-beta.8
  http: ^1.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  provider: ^6.1.5
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  firebase_storage: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  build_runner: ^2.5.0
  json_serializable: ^6.9.0
  flutter_lints: ^4.0.0
  talawa_lint:
    path: talawa_lint

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/translations/
