# pubspec.yaml
name: talawa_lint
environment:
  sdk: ">=2.19.0 <4.0.0"

dev_dependencies:
  lint: ^2.3.0
  args: ^2.4.2

dependencies:
  # we will use analyzer for inspecting Dart files
  analyzer: ">=5.12.0 <=7.3.0"
  analyzer_plugin: ^0.13.0
  # args:
  
  # custom_lint_builder will give us tools for writing lints
  custom_lint: ^0.7.0
  custom_lint_builder: ^0.7.0
  # watcher: ^1.1.0
