# pubspec.yaml
name: talawa_lint
environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  lint: ^2.3.0

dependencies:
  analyzer: ">=8.0.0 <9.0.0"
  custom_lint: ^0.8.1
  custom_lint_builder: ^0.8.1
  analyzer_plugin: ^0.13.0

  # custom_lint_builder will give us tools for writing lints
  args: ^2.4.2

  # watcher: ^1.1.0
  
