# pubspec.yaml
name: talawa_lint
environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  lint: ^2.3.0

dependencies:
  # we will use analyzer for inspecting Dart files
  # _fe_analyzer_shared: ^61.0.0
  analyzer: any
  analyzer_plugin: any
  # args:

  # custom_lint_builder will give us tools for writing lints
  args: ^2.4.2
  custom_lint: any
  custom_lint_builder: any
  # watcher: ^1.1.0
