# pubspec.yaml
name: talawa_lint
environment:
  sdk: ">=3.0.0 <4.0.0" 

dev_dependencies:
  lint: ^2.3.0
  # we will use analyzer for inspecting Dart files
  # _fe_analyzer_shared: ^61.0.0
  analyzer: ^6.4.0
  analyzer_plugin: ^0.11.3
  args: ^2.4.2
  # watcher: ^1.1.0
