name: talawa_lint

environment:
  sdk: ">=3.5.0 <4.0.0"  # Works with Dart 3.5.3 exactly

dev_dependencies:
  lint: ^2.6.0            
  custom_lint: 0.6.4
  custom_lint_builder: 0.6.4

dependencies:
  analyzer: ">=5.12.0 <6.5.0"   # Safe for Dart 3.5.x
  analyzer_plugin: ^0.11.2
  args: ^2.4.2
