##############################################################################
##############################################################################
#
# NOTE!
#
# Please read the README.md file in this directory that defines what should
# be placed in this file.
#
##############################################################################
##############################################################################

---
name: Generate Dart Documentation (HTML)

on:
  push:
    branches:
      - "main"
    paths:
      - "lib/**"
      - "pubspec.yaml"
  pull_request:
    branches:
      - "main"
    paths:
      - "lib/**"
      - "pubspec.yaml"
env:
  FLUTTER_VERSION: "3.24.0"

jobs:
  generate-docs:
    if: ${{ github.actor != 'dependabot[bot]'  && github.actor != 'github-actions[bot]'  }}
    name: Generate Dart Docs (HTML)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Generate Dart Documentation (MARKDOWN)
        run: |
          mkdir -p docs/auto-docs
          dart doc -o docs/auto-docs

      - name: Verify docs were created
        run: |
          if [ ! -d "docs/auto-docs" ]; then
            echo "‚ùå Docs directory not created!"
            exit 1
          fi

      - name: Commit and push generated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/auto-docs
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: update auto-generated Dart docs"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
