name: Issue Workflow
on:
  issues:
    types: ['opened']
jobs:
 Opened-issue-label:
    uses: PalisadoesFoundation/.github/.github/workflows/issue.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}