##############################################################################
##############################################################################
#
# NOTE!
#
# Please read the README.md file in this directory that defines what should 
# be placed in this file
#
##############################################################################
##############################################################################

name: Issue Assignment Workflow
on:
  issues:
    types: ['assigned']

jobs:
  Remove-Unapproved-Label:
    uses: PalisadoesFoundation/.github/.github/workflows/issue-assigned.yml@main
